// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwDzEvYCM60arSJQwWL-dzKgnkHRQUU_M',
    appId: '1:135545929899:web:45e6352459244f5f4937ee',
    messagingSenderId: '135545929899',
    projectId: 'sachin-nagwade',
    authDomain: 'sachin-nagwade.firebaseapp.com',
    storageBucket: 'sachin-nagwade.firebasestorage.app',
    measurementId: 'G-F1410VXR2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZhFTlC7TtBlkyyfE8LxcJdT_lKm1wfpw',
    appId: '1:135545929899:android:a1bc7df96001b43d4937ee',
    messagingSenderId: '135545929899',
    projectId: 'sachin-nagwade',
    storageBucket: 'sachin-nagwade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkzT3CvrzQ5jUHDBu7yLRS5V36NwTEpLo',
    appId: '1:135545929899:ios:0bee43a8c187efa84937ee',
    messagingSenderId: '135545929899',
    projectId: 'sachin-nagwade',
    storageBucket: 'sachin-nagwade.firebasestorage.app',
    iosBundleId: 'com.core3.in.sachinNagwade',
  );
}
